"""drop review fields from document_versions

Revision ID: 08b447fdcfe7
Revises: 3bf7d6c48df2
Create Date: 2026-07-28 11:02:57.181251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '08b447fdcfe7'
down_revision: Union[str, None] = '3bf7d6c48df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'reviewed_by')
    op.drop_column('document_versions', 'reviewed_at')
    op.drop_column('document_versions', 'customer_summary')
    op.drop_column('document_versions', 'eu_eea_relevant')
    op.drop_column('document_versions', 'reviewed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('document_versions', sa.Column('eu_eea_relevant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('document_versions', sa.Column('customer_summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('document_versions', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_versions', sa.Column('reviewed_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
