"""create tracker tables

Revision ID: 0ec478ee63f4
Revises: 
Create Date: 2026-07-27 15:26:29.003833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ec478ee63f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'slug')
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('authority', sa.Enum('contractual', 'official_legal', 'official_product_documentation', 'official_trust_center', 'official_release_notes', 'official_api', 'official_blog', 'official_support', 'official_forum_staff', 'secondary_reputable', 'community', name='source_authority'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_healthy_age_seconds', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=500), nullable=True),
    sa.Column('last_modified', sa.String(length=200), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'source_key')
    )
    op.create_table('source_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=True),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_content', sa.String(), nullable=False),
    sa.Column('normalized_content', sa.String(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'normalized_sha256')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_versions')
    op.drop_table('source_observations')
    op.drop_table('sources')
    op.drop_table('products')
    op.drop_table('providers')
    # ### end Alembic commands ###
    # drop_table alone leaves the Postgres enum type behind (autogenerate
    # limitation) - drop it explicitly so a downgrade+upgrade cycle doesn't
    # collide on "type already exists".
    sa.Enum(name='source_authority').drop(op.get_bind(), checkfirst=True)
