"""add source_class, registry corroboration, evidence offsets

Revision ID: 17f81db6cc5a
Revises: 2aba65e8f273
Create Date: 2026-07-29 13:10:21.551568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17f81db6cc5a'
down_revision: Union[str, None] = '2aba65e8f273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


source_class_enum = sa.Enum(
    'legal_notice', 'privacy_security', 'trust_center', 'region_matrix', 'changelog', 'other',
    name='source_class',
)


def upgrade() -> None:
    source_class_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('eu_eea_evidence_char_start', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('eu_eea_evidence_char_end', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_evidence_char_start', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_evidence_char_end', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_conflicting_quote', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_conflicting_source_id', sa.Uuid(), nullable=True))
    op.add_column('providers', sa.Column('registry_verified_country', sa.String(length=2), nullable=True))
    op.add_column('providers', sa.Column('registry_source', sa.String(length=20), nullable=True))
    op.add_column('providers', sa.Column('registry_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'sources',
        sa.Column(
            'source_class',
            source_class_enum,
            nullable=False,
            server_default='other',
        ),
    )
    # ### end Alembic commands ###

    # Backfill existing rows from their existing authority tagging, which
    # already roughly encodes page type: official_legal/contractual sources
    # are legal-notice/ToS-type pages, official_trust_center is a trust
    # center, official_release_notes is a changelog. Everything else stays
    # the 'other' default above rather than guessing.
    op.execute("UPDATE sources SET source_class = 'legal_notice' WHERE authority IN ('official_legal', 'contractual')")
    op.execute("UPDATE sources SET source_class = 'trust_center' WHERE authority = 'official_trust_center'")
    op.execute("UPDATE sources SET source_class = 'changelog' WHERE authority = 'official_release_notes'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_class')
    op.drop_column('providers', 'registry_checked_at')
    op.drop_column('providers', 'registry_source')
    op.drop_column('providers', 'registry_verified_country')
    op.drop_column('providers', 'eu_domicile_conflicting_source_id')
    op.drop_column('providers', 'eu_domicile_conflicting_quote')
    op.drop_column('providers', 'eu_domicile_evidence_char_end')
    op.drop_column('providers', 'eu_domicile_evidence_char_start')
    op.drop_column('products', 'eu_eea_evidence_char_end')
    op.drop_column('products', 'eu_eea_evidence_char_start')
    # ### end Alembic commands ###

    source_class_enum.drop(op.get_bind(), checkfirst=True)
