"""add eu_domicile status to providers

Revision ID: 2aba65e8f273
Revises: 3ad327506e69
Create Date: 2026-07-28 11:39:10.206331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2aba65e8f273'
down_revision: Union[str, None] = '3ad327506e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'providers',
        sa.Column('eu_domicile_status', sa.String(length=20), nullable=False, server_default='unclear'),
    )
    op.add_column('providers', sa.Column('eu_domicile_evidence_quote', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_evidence_source_id', sa.Uuid(), nullable=True))
    op.add_column('providers', sa.Column('eu_domicile_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'eu_domicile_evaluated_at')
    op.drop_column('providers', 'eu_domicile_evidence_source_id')
    op.drop_column('providers', 'eu_domicile_evidence_quote')
    op.drop_column('providers', 'eu_domicile_status')
    # ### end Alembic commands ###
