"""add eu_eea residency status to products

Revision ID: 3ad327506e69
Revises: 08b447fdcfe7
Create Date: 2026-07-28 11:14:51.732607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ad327506e69'
down_revision: Union[str, None] = '08b447fdcfe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('eu_eea_status', sa.String(length=20), nullable=False, server_default='unclear'),
    )
    op.add_column('products', sa.Column('eu_eea_evidence_quote', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('eu_eea_evidence_source_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('eu_eea_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'eu_eea_evaluated_at')
    op.drop_column('products', 'eu_eea_evidence_source_id')
    op.drop_column('products', 'eu_eea_evidence_quote')
    op.drop_column('products', 'eu_eea_status')
    # ### end Alembic commands ###
