"""add review fields to document_versions

Revision ID: 3bf7d6c48df2
Revises: 0ec478ee63f4
Create Date: 2026-07-28 09:35:19.102400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bf7d6c48df2'
down_revision: Union[str, None] = '0ec478ee63f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'document_versions',
        sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('document_versions', sa.Column('eu_eea_relevant', sa.Boolean(), nullable=True))
    op.add_column('document_versions', sa.Column('customer_summary', sa.String(length=2000), nullable=True))
    op.add_column('document_versions', sa.Column('reviewed_by', sa.String(length=200), nullable=True))
    op.add_column('document_versions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'reviewed_at')
    op.drop_column('document_versions', 'reviewed_by')
    op.drop_column('document_versions', 'customer_summary')
    op.drop_column('document_versions', 'eu_eea_relevant')
    op.drop_column('document_versions', 'reviewed')
    # ### end Alembic commands ###
